/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package logon;

import Clases.Hash;
import Clases.conexion;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author digitacion-6
 */
public class Login extends javax.swing.JFrame {

    private String user,contrasenia,UserName;
    
conexion con = new conexion();
    /**
     * Creates new form Login
     */
    public Login() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        user="";contrasenia="";UserName="";
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PImagenLogin = new org.edisoncor.gui.panel.PanelImage();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        PanelLogon = new org.edisoncor.gui.panel.Panel();
        panel1 = new org.edisoncor.gui.panel.Panel();
        Lbltitulo = new org.edisoncor.gui.label.LabelMetric();
        LblUser = new org.edisoncor.gui.label.LabelMetric();
        TxtUser = new org.edisoncor.gui.textField.TextField();
        LblClave = new org.edisoncor.gui.label.LabelMetric();
        Txtclave = new org.edisoncor.gui.passwordField.PasswordField();
        LblClave1 = new org.edisoncor.gui.label.LabelMetric();
        ComboAT = new javax.swing.JComboBox();
        BtnSalir = new org.edisoncor.gui.button.ButtonColoredAction();
        BtnIniciar = new org.edisoncor.gui.button.ButtonColoredAction();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PImagenLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        PImagenLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PImagenLoginMouseMoved(evt);
            }
        });

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        PanelLogon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 151, 224)));
        PanelLogon.setColorPrimario(new java.awt.Color(41, 152, 201));

        Lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbltitulo.setText("SEGURIDAD DE AUTENTICACION REQUERIDA");
        Lbltitulo.setDistanciaDeSombra(2);
        Lbltitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lbltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lbltitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        LblUser.setText("Usuario:");
        LblUser.setDistanciaDeSombra(2);

        TxtUser.setBackground(new java.awt.Color(254, 254, 254));
        TxtUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));
        TxtUser.setForeground(new java.awt.Color(52, 117, 151));
        TxtUser.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUserActionPerformed(evt);
            }
        });

        LblClave.setText("Contraseña:");
        LblClave.setDistanciaDeSombra(2);

        Txtclave.setBackground(new java.awt.Color(255, 255, 255));
        Txtclave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));
        Txtclave.setForeground(new java.awt.Color(52, 117, 151));
        Txtclave.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Txtclave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtclaveKeyPressed(evt);
            }
        });

        LblClave1.setText("Area Trabajo");
        LblClave1.setDistanciaDeSombra(2);

        ComboAT.setForeground(new java.awt.Color(22, 166, 239));
        ComboAT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMINISTRADOR", "PERSONAL", "NORMAL" }));
        ComboAT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 166, 239)));
        ComboAT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BtnSalir.setBackground(new java.awt.Color(254, 30, 49));
        BtnSalir.setText("SALIR");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        BtnIniciar.setBackground(new java.awt.Color(33, 225, 106));
        BtnIniciar.setText("INICIAR");
        BtnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLogonLayout = new javax.swing.GroupLayout(PanelLogon);
        PanelLogon.setLayout(PanelLogonLayout);
        PanelLogonLayout.setHorizontalGroup(
            PanelLogonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLogonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelLogonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblClave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLogonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLogonLayout.createSequentialGroup()
                            .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(TxtUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Txtclave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboAT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelLogonLayout.setVerticalGroup(
            PanelLogonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogonLayout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(TxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblClave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(PanelLogonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PImagenLoginLayout = new javax.swing.GroupLayout(PImagenLogin);
        PImagenLogin.setLayout(PImagenLoginLayout);
        PImagenLoginLayout.setHorizontalGroup(
            PImagenLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PImagenLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PImagenLoginLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(PanelLogon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        PImagenLoginLayout.setVerticalGroup(
            PImagenLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PImagenLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(PanelLogon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        getContentPane().add(PImagenLogin, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUserActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
    this.dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    CambiarLimite();
    }//GEN-LAST:event_formWindowOpened

    private void PImagenLoginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PImagenLoginMouseMoved
        CambiarLimite();
    }//GEN-LAST:event_PImagenLoginMouseMoved

    private void BtnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarActionPerformed
//        try {
//             IniciarSesion(TxtUser.getText(),Hash.getStringMessageDigest(Txtclave.getText(),Hash.SHA512) );
//        } catch (Exception e) {
//            e.getMessage();
//        }
    
            new Principal().setVisible(true);
            dispose();
    //            IniciarSesion();
        
        
    }//GEN-LAST:event_BtnIniciarActionPerformed

    private void TxtclaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtclaveKeyPressed
        if(evt.getKeyChar()==evt.VK_ENTER){
            try {
                IniciarSesion();    
            } 
            catch (Exception e) {
                e.getMessage();
            }
        }
    }//GEN-LAST:event_TxtclaveKeyPressed
    public void CambiarLimite(){
        PanelLogon.setLocation((PImagenLogin.getWidth()/2)-(PanelLogon.getWidth()/2), (PImagenLogin.getHeight()/2)-(PanelLogon.getHeight()/2));
 panelImage1.setSize((PImagenLogin.getWidth()/2)+20, 50);
    panelImage1.setLocation((PImagenLogin.getWidth()/2)-(panelImage1.getWidth()/2), (PImagenLogin.getHeight()/8));
    
    PanelLogon.setColorPrimario(new Color(41,152,201, 80));
        PanelLogon.setColorSecundario(new Color(0, 0, 0, 70));
    }
    public void IniciarSesion() throws SQLException{
       int valor=0;
        try{
            con.conectar();
            
            ResultSet rs =null; 
                    rs=con.consulta("SELECT count(*) as total FROM Empleados WHERE Emp_usuario='"+TxtUser.getText()+"' AND Emp_clave='"+Txtclave.getText()+"';");
            valor = rs.getInt(1);
            JOptionPane.showMessageDialog(PanelLogon, "Este  valor: "+valor);
            
            
                if(valor == 1)
                {
                   new Principal().setVisible(true);
                    dispose();

                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Usuario no registrado");
                }
                
            con.cierraConexion();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, "Error de consulta. " + e.getMessage());
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonColoredAction BtnIniciar;
    private org.edisoncor.gui.button.ButtonColoredAction BtnSalir;
    private javax.swing.JComboBox ComboAT;
    private org.edisoncor.gui.label.LabelMetric LblClave;
    private org.edisoncor.gui.label.LabelMetric LblClave1;
    private org.edisoncor.gui.label.LabelMetric LblUser;
    private org.edisoncor.gui.label.LabelMetric Lbltitulo;
    private org.edisoncor.gui.panel.PanelImage PImagenLogin;
    private org.edisoncor.gui.panel.Panel PanelLogon;
    private org.edisoncor.gui.textField.TextField TxtUser;
    private org.edisoncor.gui.passwordField.PasswordField Txtclave;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
